export const API_BASE_URL = "https://api.noroff.dev/api/v1";
const register = "/auction/auth/register";
export const API_REG_URL = `${API_BASE_URL}${register}`;
const login = "/auction/auth/login";
export const API_LOGIN_URL = `${API_BASE_URL}${login}`;
const listing = "/auction/listings/";
export const API_LISTING_URL = `${API_BASE_URL}${listing}`;
const listings = "/auction/listings?sort=created&sortOrder=desc";
export const API_LISTINGS_URL = `${API_BASE_URL}${listings}`;
const create = "/auction/listings";
export const API_POST_URL = `${API_BASE_URL}${create}`;
const profile = "/auction/profiles/";
export const API_PROFILE_URL = `${API_BASE_URL}${profile}`;
